(ns spacetools.spacedoc-util.interface)

;; add your function signatures here...
(defn add-two [x])

(def children-tag-s)
(def link-type->prefix)
(def link-types)
(def max-headline-depth)
(def seps)
(def seps-left)
(def seps-right)
(defn register-node! [tag spec-k])
(defn all-tags [])
(defn explain-deepest [node])
(defn fmt-problem [node problem])
(defn hl-val->gh-id-base [hl-value])
(defn hl-val->path-id-frag [hl-value])
(defn known-node? [tag])
(defn link->link-prefix [path])
(defn node->spec-k [node])
(defn path-id? [val])
(defn relation [parent])
(defn relations [parents])
(defn same-row-child-count? [rows])
(defn tag->spec-k [node-tag])
(defn up-tags [spaceroot file root-node])
(defn non-blank-string? [s])
(defn any-headline-node? [node])
(defn root-node? [node])
(defn assoc-level-and-path-id [node])
(defn assoc-level-and-path-id [parent-node node])
