(ns spacetools.spacedoc-util.interface)

;; add your function signatures here...
(defn add-two [x])

(def children-tag-s)
(def link-type->prefix)
(def link-types)
(def max-headline-depth)
(def seps)
(def seps-left)
(def seps-right)
(defmacro register-node! [tag spec-k])
(defn all-tags [])
(defn explain-deepest [node])
(defn fill-hl [hl])
(defn fill-hl [p-hl hl])
(defn fmt-problem [node problem])
(defn hl-val->gh-id-base [hl-value])
(defn hl-val->path-id-frag [hl-value])
(defn known-node? [tag])
(defn link->link-prefix [path])
(defn node->spec-k [node])
(defn path-id? [val])
(defn relation [parent])
(defn relations [parents])
(defn same-row-length? [table-children])
(defn tag->spec-k [node-tag])
(defn up-tags [spaceroot file root-node])