(ns spacetools.spacedoc-util.interface)

(def link-type->prefix)
(def link-types)
(def seps)
(def seps-left)
(def seps-right)
(defn node->children-tag-s [node])
(defn register-node! [tag spec-k])
(defn all-tags [])
(defn explain-deepest [node])
(defn fmt-problem [node problem])
(defn hl-val->gh-id-base [hl-value])
(defn hl-val->path-id-frag [hl-value])
(defn known-node? [tag])
(defn link->link-prefix [path])
(defn node->spec-k [node])
(defn path-id? [val])
(defn relation [parent])
(defn relations [parents])
(defn same-row-child-count? [rows])
(defn tag->spec-k [node-tag])
(defn up-tags [spaceroot file root-node])
(defn non-blank-string? [s])
(defn any-headline-node? [node])
(defn root-node? [node])
(defn assoc-level-and-path-id [node])
(defn assoc-level-and-path-id [parent-node node])
(defn in-hl-level-range? [level])
(def toc-hl-val)
(def toc-max-depth)
(defn fmt-hl-val [hl-val])
(defn fmt-link [link-type link])
(defn fmt-str [rep-map text])
(defn fmt-text [text])
(defn indent [indent-level s])
(def max-headline-depth)
