#!/usr/bin/env bash

cd "$(dirname "$0")"

action="$1"
shift

print_help () {
read -d '' help <<- EOF
  Spacemacs documentation tools

  usage: run ACTION [OPTIONS]... [ARGS]...

  Actions:
    validate  [-i INPUT]+                 Validate input spacedoc(.SDN) files.
    describe  SPEC                        Describe spec by keyword. Example: ":spacedoc.data/root".
    rel-graph [-i INPUT]+ OUT_FILE        Draw SVG of node relations in the input spacedoc(.SDN) files.
    relations [-i INPUT]+                 Print node relations in the input Spacedoc(.SDN) files.
    format    [FILES/DIRS]...             Format .ORG files Specified directly or by parent directory.
    export    DOCS_ROOT   [FILES/DIRS]... Export .ORG files to SDN format. Export directory is "spacedoc/emacs-tools/export/target/". DOCS_ROOT is a root directory of Spacemacs documentation (usually "~/.emacs.d/"). If an argument is a directory it will be scaned for .ORG files and they will be exported. If only the first argument is supplied a default list of Spacemacs documentation files will be used.
EOF
echo "$help"
}

case $action in
"")
    print_help
    exit 2
    ;;
-h|--help)
    print_help
    exit 0
    ;;
esac

case $@ in
"")
    print_help
    exit 2
    ;;
-h|--help)
    print_help
    exit 0
    ;;
esac

case $action in
export)
    exec emacs -batch -l ./emacs-tools/export/run.el -no-site-file -q "$@"
    ;;
format)
    exec emacs -batch -l ./emacs-tools/docfmt/run.el -no-site-file -q "$@"
    ;;
describe|rel-graph|validate|relations)
    exec sdn $action "$@"
    ;;
*)
   print_help
   exit 2
  ;;
esac
